github: ["adityajanjanam"]
ko_fi: "adityajanjanam" # Your Ko-fi profile
buy_me_a_coffee: "adityajanjanam" # Your Buy Me a Coffee profile
custom: ["https://linktr.ee/adityajanjanam"] # Linktree for multiple profiles
