services:
  - type: web
    name: trainwithtail-web
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        sync: false
      - key: MONGO_URI
        sync: false 